language: node_js
node_js:
  - "stable"
install: 
  - npm install
script: 
  - CI=false npm run build
deploy:
  - provider: s3
    bucket: "ak-ui-dev-s3"
    region: us-east-2
    on:
      branch:
        - dev
    skip_cleanup: true
    local_dir: build
  - provider: s3
    bucket: "ak-ui-prod-s3"
    region: us-east-2
    on:
      branch:
        - prod
    skip_cleanup: true
    local_dir: build
