language: node_js
node_js:
  - node
install: true
script: skip
deploy:
  - provider: s3
    bucket: "ak-ui-dev-s3"
    region: us-east-2
    on:
      branch:
        - dev
  - provider: s3
    bucket: "ak-ui-prod-s3"
    region: us-east-2
    on:
      branch:
        - prod
